### ISSUE TITLE
"Error! No Internet Connection?" message.

### ISSUE THREAD

**Issue by lewinmadrid** [jonataswalker/ol-geocoder#208] opened 2020-04-20 09:14 UTC
This error message appears when using Nominatim. Occurs in the example in  jsFiddle
To fix, remove the slash at the end of the url.

Before;
    https://nominatim.openstreetmap.org/search/
After:
    https://nominatim.openstreetmap.org/search

**Comment by jonataswalker** [comment] 2020-09-28 12:36
Cannot reproduce! Are you able to provide a demo?

**Comment by jonataswalker** [comment] 2020-10-23 03:24
Closing but feel free to reopen with some reproduction.

**Closed by jonataswalker** 2020-10-23 03:24 UTC
Labels: need repro
