### ISSUE TITLE
Add Geocoder control to custom DIV

### ISSUE THREAD

**Issue by joe3950** [jonataswalker/ol-geocoder#223] opened 2020-09-30 18:28 UTC
It's not an issue but question...Sorry because of that...

Geocoder is located in the MAP div. I would like to add this control into a custom div (with id "prostor") outside the MAP div. How can I achieve that...

var geocoder = new Geocoder('nominatim', {
  provider: 'osm',
  lang: 'en',
  placeholder: 'Search for ...',
  limit: 5,
  debug: false,
  autoComplete: true,
  keepOpen: true,
});

Thank you in advance.

**Comment by jonataswalker** [comment] 2020-10-01 11:05
Not possible yet.

Duplicate of #87

**Closed by jonataswalker** 2020-10-01 11:05 UTC
