### ISSUE TITLE
Implement on my own input element

### ISSUE THREAD

**Issue by daksamedia** [jonataswalker/ol-geocoder#191] opened 2019-07-04 01:52 UTC
Hi @jonataswalker ,

Thank you for this API.

On your readme.md there are good explanation of this API.
But how could I implement it on my single input element?

Thanks in advance.

**Comment by jonataswalker** [comment] 2020-09-28 13:53
I will consider this as a duplicate of #87 okay?

**Closed by jonataswalker** 2020-09-28 13:53 UTC
